version: '3.9' # optional since v1.27.0
services:

  shishahub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - '3011:3011'
    expose:
    - 3011
    env_file: ./.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DB: ${DB_DB}
      VIRTUAL_HOST: ekdotikos.shishahub.online # the incomming domain name for this site
      VIRTUAL_PORT: 3011 # the port your applicatio
      LETSENCRYPT_HOST: ekdotikos.shishahub.online # the domain name to issue cert to, same as VIRTUAL_HOST
      LETSENCRYPT_EMAIL: sipmarch7@hotmail.com

networks:
  default:
    external:
      name: nginx-proxy